hero_chassis_controller:
  #底盘加速度参数
  chassis_acceleration: 2.0
  #速度模式参数
  #0代表底盘坐标系速度模式，1代表全局坐标系速度模式
  speed_mode: 1
  #底盘参数部分
  chassis:
    wheelbase: 0.4
    trackwidth: 0.4
    wheel_radius: 0.07625
  #pid参数部分
  pid:
    left_front_wheel:
      p: 0.5
      i: 0.1
      d: 0.05
    right_front_wheel:
      p: 0.5
      i: 0.1
      d: 0.05
    left_back_wheel:
      p: 0.5
      i: 0.1
      d: 0.05
    right_back_wheel:
      p: 0.5
      i: 0.1
      d: 0.05
